# Generated by Django 4.1.2 on 2023-04-23 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rec', '0002_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'AI'), ('4', 'CDS'), ('5', 'ECE'), ('6', 'EEE'), ('7', 'MECH'), ('8', 'CIVIL'), ('9', 'MINING'), ('10', 'META')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
