# Generated by Django 4.1.2 on 2023-04-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_rename_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('AI', 'AI'), ('CDS', 'CDS'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('MINING', 'MINING'), ('META', 'META')], max_length=20),
        ),
    ]
