# Generated by Django 4.1.2 on 2023-04-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0007_profile_branch1_alter_profile_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='branch',
            new_name='choose_branch1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branch1',
        ),
        migrations.AddField(
            model_name='profile',
            name='choose_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='rec.branch'),
        ),
    ]
