# Generated by Django 4.1.2 on 2023-04-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0008_rename_branch_profile_choose_branch1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='choose_branch1',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choose_branch',
        ),
    ]
