# Generated by Django 4.1.2 on 2023-04-24 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0013_company_applied_alter_company_branches_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='rec.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
