# Generated by Django 4.1.2 on 2023-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0014_remove_company_post_posts_comp_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='branch_open',
            field=models.ManyToManyField(blank=True, related_name='posts', to='rec.branch'),
        ),
        migrations.AddField(
            model_name='posts',
            name='cgpa_cutoff',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
