# Generated by Django 4.1.2 on 2023-04-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0015_posts_branch_open_posts_cgpa_cutoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cgpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('cgpa_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgpa', to='rec.branch')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgpa', to='rec.posts')),
            ],
        ),
    ]
