# Generated by Django 4.1.2 on 2023-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0016_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='cgpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
