# Generated by Django 4.1.2 on 2023-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0021_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], null=True),
        ),
    ]
