# Generated by Django 4.1.2 on 2023-04-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0022_profile_cgpa_profile_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cgpa',
            new_name='student_cgpa',
        ),
    ]
