# Generated by Django 4.1.2 on 2023-04-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0024_alter_cgpa_cgpa_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_cgpa', to='rec.posts'),
        ),
    ]
