# Generated by Django 4.1.2 on 2023-04-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0025_alter_cgpa_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgpa',
            old_name='cgpa',
            new_name='cutoff_cgpa',
        ),
    ]
