# Generated by Django 4.1.2 on 2023-04-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0026_rename_cgpa_cgpa_cutoff_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
