# Generated by Django 4.1.2 on 2023-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0027_posts_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
