# Generated by Django 4.1.2 on 2023-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0029_remove_posts_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='open_time',
        ),
        migrations.AddField(
            model_name='posts',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
