# Generated by Django 4.1.2 on 2023-05-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0030_remove_posts_open_time_posts_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_cgpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
