# Generated by Django 4.1.2 on 2023-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0031_alter_profile_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
