# Generated by Django 4.1.2 on 2023-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0032_posts_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
