# Generated by Django 4.1.2 on 2023-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0033_posts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
