# Generated by Django 4.1.2 on 2023-05-01 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rec', '0034_alter_posts_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('applied_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_details', to='rec.posts')),
                ('applied_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_posts', to='rec.profile')),
            ],
        ),
    ]
